# docker-compose version
version: '2'
# containers
services:
  nginx:
    # the latest stable nginx image
    image: nginx:latest
    ports:
      - "8081:8080"
      - "4444:4443"
    user: ${OPEN_GENES_UID}
    # mount directories from:to
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx:/etc/nginx/conf.d
      - ./app:/var/www
      - ./../open-genes-logs:/var/log/nginx
    # link nginx container to php container
    links:
      - cms
    networks:
      - default
  cms:
    # path to our PHP image that will be built
    build: ./docker/php${PHP_IMAGE_ALTER}
    # mount project's dir
    user: ${OPEN_GENES_UID}
    volumes:
      - ./app:/var/www
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: client_host=${CLIENT_HOST} client_port=9003
    image: open_genes_cms
    command: bash -c "XDEBUG_CONFIG= composer install && php /var/www/console/yii.php migrate --interactive=0 && php-fpm"
    networks:
      - db_net
      - default
  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password 
#    --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" 
    --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3307:3306"
    user: ${OPEN_GENES_UID}
    environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: open_genes
#      MYSQL_USER: sandbox_user
#      MYSQL_PASSWORD: passpass
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./../open-genes-mysql:/var/lib/mysql
      - ./docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_net

networks:
  db_net:
    external:
      name: db_net
  default:
    external: false
