# docker-compose version
version: '2'
# containers
services:
  nginx:
    # the latest stable nginx image
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    # mount directories from:to
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www
      - ./logs:/var/log/nginx
    # link nginx container to php container
    links:
      - php
  php:
    # path to our PHP image that will be built
    build: ./docker/php
    # link it to mysql
    links:
      - mysql
      - node
    # mount project's dir
    volumes:
      - .:/var/www
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./../mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
  node:
    image: catchdigital/node-sass
    volumes:
      - .:/var/www/
    command: npm run sass